from enum import Enum

class ManualTestOpcode(Enum):
    MANUAL_TEST_REGISTER_REQ = 1
    MANUAL_TEST_REGISTER_RES = 2

    MANUAL_TEST_UNREGISTER_REQ = 3
    MANUAL_TEST_UNREGISTER_RES = 4

    MANUAL_TEST_CALL_REQ = 5
    MANUAL_TEST_CALL_RES = 6

    MANUAL_TEST_HANGUP_REQ = 7
    MANUAL_TEST_HANGUP_RES = 8
    
    MANUAL_TEST_ANSWER_REQ = 9
    MANUAL_TEST_ANSWER_RES = 10

    MANUAL_TEST_DECLINE_REQ = 11
    MANUAL_TEST_DECLINE_RES = 12  