from PyQt5 import QtCore, QtWidgets
from CheckableComboBox import CheckableComboBox
from LogPopupWindow import LogPopupWindow
from PyQt5.QtWidgets import *

class Ui_MainWindow(QtWidgets.QMainWindow):

    auto_test_signal = QtCore.pyqtSignal(str, str)
    manual_test_register_signal = QtCore.pyqtSignal(int, str, str)
    manual_test_unregister_signal = QtCore.pyqtSignal(int)
    manual_test_call_signal = QtCore.pyqtSignal(int, str)
    manual_test_hangup_signal = QtCore.pyqtSignal(int)
    manual_test_answer_signal = QtCore.pyqtSignal(int)
    manual_test_decline_signal = QtCore.pyqtSignal(int)
    connect_signal = QtCore.pyqtSignal(str, str)
    disconnect_signal = QtCore.pyqtSignal()
    print_log = QtCore.pyqtSignal(QtWidgets.QTextBrowser, str)
    item_clicked_signal = QtCore.pyqtSignal(str)
    openPopupWindow_signal = QtCore.pyqtSignal(str)
    refreshHeaders_signal = QtCore.pyqtSignal()

    def __init__(self, filterAutoTestLabel):
        super(Ui_MainWindow, self).__init__()
        self.setObjectName("MainWindow")
        self.resize(1303, 845)
        self.setAutoFillBackground(False)
        self.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(250, 0, 1050, 850))
        self.tabWidget.setObjectName("tabWidget")
        self.Auto_Tests = QtWidgets.QWidget()
        self.Auto_Tests.setObjectName("Auto_Tests")
        self.auto_tests_main_label = QtWidgets.QLabel(self.Auto_Tests)
        self.auto_tests_main_label.setGeometry(QtCore.QRect(80, 30, 475, 33))
        self.auto_tests_main_label.setObjectName("auto_tests_main_label")
        self.auto_tests_pbx_ip_edit_text = QtWidgets.QTextEdit(self.Auto_Tests)
        self.auto_tests_pbx_ip_edit_text.setGeometry(QtCore.QRect(430, 100, 261, 31))
        self.auto_tests_pbx_ip_edit_text.setObjectName("auto_tests_pbx_ip_edit_text")
        self.auto_tests_amout_edit_text = QtWidgets.QTextEdit(self.Auto_Tests)
        self.auto_tests_amout_edit_text.setGeometry(QtCore.QRect(430, 170, 261, 31))
        self.auto_tests_amout_edit_text.setObjectName("auto_tests_amout_edit_text")
        self.auto_tests_button = QtWidgets.QPushButton(self.Auto_Tests)
        self.auto_tests_button.setGeometry(QtCore.QRect(760, 140, 75, 23))
        self.auto_tests_button.setObjectName("auto_tests_button")
        self.auto_tests_pbx_ip_label = QtWidgets.QLabel(self.Auto_Tests)
        self.auto_tests_pbx_ip_label.setGeometry(QtCore.QRect(270, 103, 61, 31))
        self.auto_tests_pbx_ip_label.setObjectName("auto_tests_pbx_ip_label")
        self.auto_tests_amout_label = QtWidgets.QLabel(self.Auto_Tests)
        self.auto_tests_amout_label.setGeometry(QtCore.QRect(270, 175, 125, 21))
        self.auto_tests_amout_label.setObjectName("auto_tests_amout_label")
        self.auto_tests_log_text_browser = QtWidgets.QTextBrowser(self.Auto_Tests)
        self.auto_tests_log_text_browser.setGeometry(QtCore.QRect(2, 260, 1045, 555))
        self.auto_tests_log_text_browser.setObjectName("auto_tests_log_text_browser")
        self.auto_tests_log_label = QtWidgets.QLabel(self.Auto_Tests)
        self.auto_tests_log_label.setGeometry(QtCore.QRect(10, 225, 100, 28))
        self.auto_tests_log_label.setObjectName("auto_tests_log_label")
        self.comboBox = CheckableComboBox(filterAutoTestLabel, self.Auto_Tests)
        self.comboBox.setGeometry(QtCore.QRect(950, 225, 90, 30))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.tabWidget.addTab(self.Auto_Tests, "")
        self.Manual_Tests = QtWidgets.QWidget()
        self.Manual_Tests.setObjectName("Manual_Tests")
        self.softphone_1 = QtWidgets.QFrame(self.Manual_Tests)
        self.softphone_1.setGeometry(QtCore.QRect(0, 5, 350, 800))
        self.softphone_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.softphone_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.softphone_1.setObjectName("softphone_1")
        self.softphone_text_log_label_1 = QtWidgets.QLabel(self.softphone_1)
        self.softphone_text_log_label_1.setGeometry(QtCore.QRect(2, 590, 75, 30))
        self.softphone_text_log_label_1.setObjectName("softphone_text_log_label_1")
        self.softphone_log_text_browser_1 = QtWidgets.QTextBrowser(self.softphone_1)
        self.softphone_log_text_browser_1.setGeometry(QtCore.QRect(2, 624, 346, 171))
        self.softphone_log_text_browser_1.setObjectName("softphone_log_text_browser_1")
        self.softphone_softphone_uri_header_label_1 = QtWidgets.QLabel(self.softphone_1)
        self.softphone_softphone_uri_header_label_1.setGeometry(QtCore.QRect(2, 0, 346, 40))
        self.softphone_softphone_uri_header_label_1.setObjectName("softphone_softphone_uri_header_label_1")
        self.softphone_status_label_1 = QtWidgets.QLabel(self.softphone_1)
        self.softphone_status_label_1.setGeometry(QtCore.QRect(5, 85, 55, 20))
        self.softphone_status_label_1.setObjectName("softphone_status_label_1")
        self.softphone_current_status_label_1 = QtWidgets.QLabel(self.softphone_1)
        self.softphone_current_status_label_1.setGeometry(QtCore.QRect(80, 85, 265, 20))
        self.softphone_current_status_label_1.setObjectName("softphone_current_status_label_1")
        self.softphone_register_label_1 = QtWidgets.QLabel(self.softphone_1)
        self.softphone_register_label_1.setGeometry(QtCore.QRect(5, 120, 340, 61))
        self.softphone_register_label_1.setObjectName("softphone_register_label_1")
        self.softphone_pbx_ip_edit_text_1 = QtWidgets.QTextEdit(self.softphone_1)
        self.softphone_pbx_ip_edit_text_1.setGeometry(QtCore.QRect(5, 280, 340, 40))
        self.softphone_pbx_ip_edit_text_1.setObjectName("softphone_pbx_ip_edit_text_1")
        self.softphone_call_label_1 = QtWidgets.QLabel(self.softphone_1)
        self.softphone_call_label_1.setGeometry(QtCore.QRect(5, 380, 340, 30))
        self.softphone_call_label_1.setObjectName("softphone_call_label_1")
        self.softphone_dest_edit_text_1 = QtWidgets.QTextEdit(self.softphone_1)
        self.softphone_dest_edit_text_1.setGeometry(QtCore.QRect(5, 410, 340, 40))
        self.softphone_dest_edit_text_1.setObjectName("softphone_dest_edit_text_1")
        self.softphone_answer_button_1 = QtWidgets.QPushButton(self.softphone_1)
        self.softphone_answer_button_1.setGeometry(QtCore.QRect(10, 510, 93, 28))
        self.softphone_answer_button_1.setObjectName("softphone_answer_button_1")
        self.softphone_call_button_1 = QtWidgets.QPushButton(self.softphone_1)
        self.softphone_call_button_1.setGeometry(QtCore.QRect(120, 460, 93, 28))
        self.softphone_call_button_1.setObjectName("softphone_call_button_1")
        self.softphone_register_button_1 = QtWidgets.QPushButton(self.softphone_1)
        self.softphone_register_button_1.setGeometry(QtCore.QRect(50, 330, 93, 28))
        self.softphone_register_button_1.setObjectName("softphone_register_button_1")
        self.softphone_decline_button_1 = QtWidgets.QPushButton(self.softphone_1)
        self.softphone_decline_button_1.setGeometry(QtCore.QRect(240, 510, 93, 28))
        self.softphone_decline_button_1.setObjectName("softphone_decline_button_1")
        self.softphone_uri_label_1 = QtWidgets.QLabel(self.softphone_1)
        self.softphone_uri_label_1.setGeometry(QtCore.QRect(2, 40, 346, 40))
        self.softphone_uri_label_1.setObjectName("softphone_uri_label_1")
        self.softphone_id_edit_text_1 = QtWidgets.QTextEdit(self.softphone_1)
        self.softphone_id_edit_text_1.setGeometry(QtCore.QRect(5, 210, 340, 40))
        self.softphone_id_edit_text_1.setObjectName("softphone_id_edit_text_1")
        self.softphone_id_label_1 = QtWidgets.QLabel(self.softphone_1)
        self.softphone_id_label_1.setGeometry(QtCore.QRect(10, 190, 91, 16))
        self.softphone_id_label_1.setObjectName("softphone_id_label_1")
        self.softphone_pbx_ip_label_1 = QtWidgets.QLabel(self.softphone_1)
        self.softphone_pbx_ip_label_1.setGeometry(QtCore.QRect(10, 260, 91, 16))
        self.softphone_pbx_ip_label_1.setObjectName("softphone_pbx_ip_label_1")
        self.softphone_hangup_button_1 = QtWidgets.QPushButton(self.softphone_1)
        self.softphone_hangup_button_1.setGeometry(QtCore.QRect(120, 560, 93, 28))
        self.softphone_hangup_button_1.setObjectName("softphone_hangup_button_1")
        self.softphone_unregister_button_1 = QtWidgets.QPushButton(self.softphone_1)
        self.softphone_unregister_button_1.setGeometry(QtCore.QRect(190, 330, 93, 28))
        self.softphone_unregister_button_1.setObjectName("softphone_unregister_button_1")
        self.softphone_2 = QtWidgets.QFrame(self.Manual_Tests)
        self.softphone_2.setGeometry(QtCore.QRect(350, 5, 350, 800))
        self.softphone_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.softphone_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.softphone_2.setObjectName("softphone_2")
        self.softphone_text_log_label_2 = QtWidgets.QLabel(self.softphone_2)
        self.softphone_text_log_label_2.setGeometry(QtCore.QRect(2, 590, 75, 30))
        self.softphone_text_log_label_2.setObjectName("softphone_text_log_label_2")
        self.softphone_log_text_browser_2 = QtWidgets.QTextBrowser(self.softphone_2)
        self.softphone_log_text_browser_2.setGeometry(QtCore.QRect(2, 624, 346, 171))
        self.softphone_log_text_browser_2.setObjectName("softphone_log_text_browser_2")
        self.softphone_softphone_uri_header_label_2 = QtWidgets.QLabel(self.softphone_2)
        self.softphone_softphone_uri_header_label_2.setGeometry(QtCore.QRect(2, 0, 346, 40))
        self.softphone_softphone_uri_header_label_2.setObjectName("softphone_softphone_uri_header_label_2")
        self.softphone_status_label_2 = QtWidgets.QLabel(self.softphone_2)
        self.softphone_status_label_2.setGeometry(QtCore.QRect(5, 85, 55, 20))
        self.softphone_status_label_2.setObjectName("softphone_status_label_2")
        self.softphone_current_status_label_2 = QtWidgets.QLabel(self.softphone_2)
        self.softphone_current_status_label_2.setGeometry(QtCore.QRect(80, 85, 265, 20))
        self.softphone_current_status_label_2.setObjectName("softphone_current_status_label_2")
        self.softphone_register_label_2 = QtWidgets.QLabel(self.softphone_2)
        self.softphone_register_label_2.setGeometry(QtCore.QRect(5, 120, 340, 61))
        self.softphone_register_label_2.setObjectName("softphone_register_label_2")
        self.softphone_pbx_ip_edit_text_2 = QtWidgets.QTextEdit(self.softphone_2)
        self.softphone_pbx_ip_edit_text_2.setGeometry(QtCore.QRect(5, 280, 340, 40))
        self.softphone_pbx_ip_edit_text_2.setObjectName("softphone_pbx_ip_edit_text_2")
        self.softphone_call_label_2 = QtWidgets.QLabel(self.softphone_2)
        self.softphone_call_label_2.setGeometry(QtCore.QRect(5, 380, 340, 30))
        self.softphone_call_label_2.setObjectName("softphone_call_label_2")
        self.softphone_dest_edit_text_2 = QtWidgets.QTextEdit(self.softphone_2)
        self.softphone_dest_edit_text_2.setGeometry(QtCore.QRect(5, 410, 340, 40))
        self.softphone_dest_edit_text_2.setObjectName("softphone_dest_edit_text_2")
        self.softphone_answer_button_2 = QtWidgets.QPushButton(self.softphone_2)
        self.softphone_answer_button_2.setGeometry(QtCore.QRect(10, 510, 93, 28))
        self.softphone_answer_button_2.setObjectName("softphone_answer_button_2")
        self.softphone_call_button_2 = QtWidgets.QPushButton(self.softphone_2)
        self.softphone_call_button_2.setGeometry(QtCore.QRect(120, 460, 93, 28))
        self.softphone_call_button_2.setObjectName("softphone_call_button_2")
        self.softphone_register_button_2 = QtWidgets.QPushButton(self.softphone_2)
        self.softphone_register_button_2.setGeometry(QtCore.QRect(50, 330, 93, 28))
        self.softphone_register_button_2.setObjectName("softphone_register_button_2")
        self.softphone_decline_button_2 = QtWidgets.QPushButton(self.softphone_2)
        self.softphone_decline_button_2.setGeometry(QtCore.QRect(240, 510, 93, 28))
        self.softphone_decline_button_2.setObjectName("softphone_decline_button_2")
        self.softphone_uri_label_2 = QtWidgets.QLabel(self.softphone_2)
        self.softphone_uri_label_2.setGeometry(QtCore.QRect(2, 40, 346, 40))
        self.softphone_uri_label_2.setObjectName("softphone_uri_label_2")
        self.softphone_id_edit_text_2 = QtWidgets.QTextEdit(self.softphone_2)
        self.softphone_id_edit_text_2.setGeometry(QtCore.QRect(5, 210, 340, 40))
        self.softphone_id_edit_text_2.setObjectName("softphone_id_edit_text_2")
        self.softphone_id_label_2 = QtWidgets.QLabel(self.softphone_2)
        self.softphone_id_label_2.setGeometry(QtCore.QRect(10, 190, 91, 16))
        self.softphone_id_label_2.setObjectName("softphone_id_label_2")
        self.softphone_pbx_ip_label_2 = QtWidgets.QLabel(self.softphone_2)
        self.softphone_pbx_ip_label_2.setGeometry(QtCore.QRect(10, 260, 91, 16))
        self.softphone_pbx_ip_label_2.setObjectName("softphone_pbx_ip_label_2")
        self.softphone_hangup_button_2 = QtWidgets.QPushButton(self.softphone_2)
        self.softphone_hangup_button_2.setGeometry(QtCore.QRect(120, 560, 93, 28))
        self.softphone_hangup_button_2.setObjectName("softphone_hangup_button_2")
        self.softphone_unregister_button_2 = QtWidgets.QPushButton(self.softphone_2)
        self.softphone_unregister_button_2.setGeometry(QtCore.QRect(190, 330, 93, 28))
        self.softphone_unregister_button_2.setObjectName("softphone_unregister_button_2")
        self.softphone_3 = QtWidgets.QFrame(self.Manual_Tests)
        self.softphone_3.setGeometry(QtCore.QRect(700, 5, 350, 800))
        self.softphone_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.softphone_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.softphone_3.setObjectName("softphone_3")
        self.softphone_text_log_label_3 = QtWidgets.QLabel(self.softphone_3)
        self.softphone_text_log_label_3.setGeometry(QtCore.QRect(2, 590, 75, 30))
        self.softphone_text_log_label_3.setObjectName("softphone_text_log_label_3")
        self.softphone_log_text_browser_3 = QtWidgets.QTextBrowser(self.softphone_3)
        self.softphone_log_text_browser_3.setGeometry(QtCore.QRect(2, 624, 346, 171))
        self.softphone_log_text_browser_3.setObjectName("softphone_log_text_browser_3")
        self.softphone_softphone_uri_header_label_3 = QtWidgets.QLabel(self.softphone_3)
        self.softphone_softphone_uri_header_label_3.setGeometry(QtCore.QRect(2, 0, 346, 40))
        self.softphone_softphone_uri_header_label_3.setObjectName("softphone_softphone_uri_header_label_3")
        self.softphone_status_label_3 = QtWidgets.QLabel(self.softphone_3)
        self.softphone_status_label_3.setGeometry(QtCore.QRect(5, 85, 55, 20))
        self.softphone_status_label_3.setObjectName("softphone_status_label_3")
        self.softphone_current_status_label_3 = QtWidgets.QLabel(self.softphone_3)
        self.softphone_current_status_label_3.setGeometry(QtCore.QRect(80, 85, 265, 20))
        self.softphone_current_status_label_3.setObjectName("softphone_current_status_label_3")
        self.softphone_register_label_3 = QtWidgets.QLabel(self.softphone_3)
        self.softphone_register_label_3.setGeometry(QtCore.QRect(5, 120, 340, 61))
        self.softphone_register_label_3.setObjectName("softphone_register_label_3")
        self.softphone_pbx_ip_edit_text_3 = QtWidgets.QTextEdit(self.softphone_3)
        self.softphone_pbx_ip_edit_text_3.setGeometry(QtCore.QRect(5, 280, 340, 40))
        self.softphone_pbx_ip_edit_text_3.setObjectName("softphone_pbx_ip_edit_text_3")
        self.softphone_call_label_3 = QtWidgets.QLabel(self.softphone_3)
        self.softphone_call_label_3.setGeometry(QtCore.QRect(5, 380, 340, 30))
        self.softphone_call_label_3.setObjectName("softphone_call_label_3")
        self.softphone_dest_edit_text_3 = QtWidgets.QTextEdit(self.softphone_3)
        self.softphone_dest_edit_text_3.setGeometry(QtCore.QRect(5, 410, 340, 40))
        self.softphone_dest_edit_text_3.setObjectName("softphone_dest_edit_text_3")
        self.softphone_answer_button_3 = QtWidgets.QPushButton(self.softphone_3)
        self.softphone_answer_button_3.setGeometry(QtCore.QRect(10, 510, 93, 28))
        self.softphone_answer_button_3.setObjectName("softphone_answer_button_3")
        self.softphone_call_button_3 = QtWidgets.QPushButton(self.softphone_3)
        self.softphone_call_button_3.setGeometry(QtCore.QRect(120, 460, 93, 28))
        self.softphone_call_button_3.setObjectName("softphone_call_button_3")
        self.softphone_register_button_3 = QtWidgets.QPushButton(self.softphone_3)
        self.softphone_register_button_3.setGeometry(QtCore.QRect(50, 330, 93, 28))
        self.softphone_register_button_3.setObjectName("softphone_register_button_3")
        self.softphone_decline_button_3 = QtWidgets.QPushButton(self.softphone_3)
        self.softphone_decline_button_3.setGeometry(QtCore.QRect(240, 510, 93, 28))
        self.softphone_decline_button_3.setObjectName("softphone_decline_button_3")
        self.softphone_uri_label_3 = QtWidgets.QLabel(self.softphone_3)
        self.softphone_uri_label_3.setGeometry(QtCore.QRect(2, 40, 346, 40))
        self.softphone_uri_label_3.setObjectName("softphone_uri_label_3")
        self.softphone_id_edit_text_3 = QtWidgets.QTextEdit(self.softphone_3)
        self.softphone_id_edit_text_3.setGeometry(QtCore.QRect(5, 210, 340, 40))
        self.softphone_id_edit_text_3.setObjectName("softphone_id_edit_text_3")
        self.softphone_id_label_3 = QtWidgets.QLabel(self.softphone_3)
        self.softphone_id_label_3.setGeometry(QtCore.QRect(10, 190, 91, 16))
        self.softphone_id_label_3.setObjectName("softphone_id_label_3")
        self.softphone_pbx_ip_label_3 = QtWidgets.QLabel(self.softphone_3)
        self.softphone_pbx_ip_label_3.setGeometry(QtCore.QRect(10, 260, 91, 16))
        self.softphone_pbx_ip_label_3.setObjectName("softphone_pbx_ip_label_3")
        self.softphone_hangup_button_3 = QtWidgets.QPushButton(self.softphone_3)
        self.softphone_hangup_button_3.setGeometry(QtCore.QRect(120, 560, 93, 28))
        self.softphone_hangup_button_3.setObjectName("softphone_hangup_button_3")
        self.softphone_unregister_button_3 = QtWidgets.QPushButton(self.softphone_3)
        self.softphone_unregister_button_3.setGeometry(QtCore.QRect(190, 330, 93, 28))
        self.softphone_unregister_button_3.setObjectName("softphone_unregister_button_3")
        self.tabWidget.addTab(self.Manual_Tests, "")
        self.History = QtWidgets.QWidget()
        self.History.setObjectName("History")
        self.Log_History_Label = QtWidgets.QLabel(self.History)
        self.Log_History_Label.setGeometry(QtCore.QRect(20, 10, 151, 51))
        self.Log_History_Label.setObjectName("Log_History_Label")
        self.Log_History_List_Widget = QtWidgets.QListWidget(self.History)
        self.Log_History_List_Widget.setGeometry(QtCore.QRect(2, 70, 1041, 741))
        self.Log_History_List_Widget.setObjectName("Log_History_List_Widget")
        self.Log_History_Refresh_button = QtWidgets.QPushButton(self.History)
        self.Log_History_Refresh_button.setGeometry(QtCore.QRect(920, 20, 100, 40))
        self.Log_History_Refresh_button.setObjectName("Log_History_Refresh_button")
        self.tabWidget.addTab(self.History, "")
        self.About = QtWidgets.QWidget()
        self.About.setObjectName("About")
        self.About_label = QtWidgets.QLabel(self.About)
        self.About_label.setGeometry(QtCore.QRect(20, 10, 991, 261))
        self.About_label.setAutoFillBackground(False)
        self.About_label.setScaledContents(False)
        self.About_label.setObjectName("About_label")
        self.tabWidget.addTab(self.About, "")
        self.VoIP_Tester_Label = QtWidgets.QLabel(self.centralwidget)
        self.VoIP_Tester_Label.setGeometry(QtCore.QRect(0, 0, 250, 250))
        self.VoIP_Tester_Label.setObjectName("VoIP_Tester_Label")
        self.connect_frame = QtWidgets.QFrame(self.centralwidget)
        self.connect_frame.setGeometry(QtCore.QRect(0, 250, 250, 600))
        self.connect_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connect_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connect_frame.setObjectName("connect_frame")
        self.connect_frame_Connect_button = QtWidgets.QPushButton(self.connect_frame)
        self.connect_frame_Connect_button.setGeometry(QtCore.QRect(80, 400, 75, 23))
        self.connect_frame_Connect_button.setObjectName("connect_frame_Connect_button")
        self.connect_frame_ip_edit_text = QtWidgets.QTextEdit(self.connect_frame)
        self.connect_frame_ip_edit_text.setGeometry(QtCore.QRect(30, 270, 181, 31))
        self.connect_frame_ip_edit_text.setObjectName("connect_frame_ip_edit_text")
        self.connect_frame_text_label = QtWidgets.QLabel(self.connect_frame)
        self.connect_frame_text_label.setGeometry(QtCore.QRect(13, 80, 231, 121))
        self.connect_frame_text_label.setObjectName("connect_frame_text_label")
        self.connect_frame_ip_label = QtWidgets.QLabel(self.connect_frame)
        self.connect_frame_ip_label.setGeometry(QtCore.QRect(30, 250, 47, 13))
        self.connect_frame_ip_label.setObjectName("connect_frame_ip_label")
        self.connect_frame_disconnect_button = QtWidgets.QPushButton(self.connect_frame)
        self.connect_frame_disconnect_button.setGeometry(QtCore.QRect(150, 560, 93, 28))
        self.connect_frame_disconnect_button.setObjectName("connect_frame_disconnect_button")
        self.connect_frame_port_edit_text = QtWidgets.QTextEdit(self.connect_frame)
        self.connect_frame_port_edit_text.setGeometry(QtCore.QRect(30, 350, 181, 31))
        self.connect_frame_port_edit_text.setObjectName("connect_frame_port_edit_text")
        self.connect_frame_port_label = QtWidgets.QLabel(self.connect_frame)
        self.connect_frame_port_label.setGeometry(QtCore.QRect(30, 330, 47, 13))
        self.connect_frame_port_label.setObjectName("connect_frame_port_label")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.auto_tests_button.clicked.connect(self.autoTestClicked)
        self.softphone_register_button_1.clicked.connect(self.manualTestRegisterClicked)
        self.softphone_register_button_2.clicked.connect(self.manualTestRegisterClicked)
        self.softphone_register_button_3.clicked.connect(self.manualTestRegisterClicked)
        self.softphone_unregister_button_1.clicked.connect(self.manualTestUnregisterClicked)
        self.softphone_unregister_button_2.clicked.connect(self.manualTestUnregisterClicked)
        self.softphone_unregister_button_3.clicked.connect(self.manualTestUnregisterClicked)
        self.softphone_call_button_1.clicked.connect(self.manualTestCallClicked)
        self.softphone_call_button_2.clicked.connect(self.manualTestCallClicked)
        self.softphone_call_button_3.clicked.connect(self.manualTestCallClicked)
        self.softphone_hangup_button_1.clicked.connect(self.manualTestHangupClicked)
        self.softphone_hangup_button_2.clicked.connect(self.manualTestHangupClicked)
        self.softphone_hangup_button_3.clicked.connect(self.manualTestHangupClicked)
        self.softphone_answer_button_1.clicked.connect(self.manualTestAnswerClicked)
        self.softphone_answer_button_2.clicked.connect(self.manualTestAnswerClicked)
        self.softphone_answer_button_3.clicked.connect(self.manualTestAnswerClicked)
        self.softphone_decline_button_1.clicked.connect(self.manualTestDeclineClicked)
        self.softphone_decline_button_2.clicked.connect(self.manualTestDeclineClicked)
        self.softphone_decline_button_3.clicked.connect(self.manualTestDeclineClicked)
        self.connect_frame_Connect_button.clicked.connect(self.connectClicked)
        self.connect_frame_disconnect_button.clicked.connect(self.disconnectClicked)
        self.Log_History_List_Widget.itemClicked.connect(self.itemClicked)
        self.Log_History_Refresh_button.clicked.connect(self.refreshHeaders)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "VoIP-Teter Controller"))
        self.auto_tests_main_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Please enter the required details below:</span></p></body></html>"))
        self.auto_tests_button.setText(_translate("MainWindow", "send"))
        self.auto_tests_pbx_ip_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">PBX IP:</span></p></body></html>"))
        self.auto_tests_amout_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Amount of calls:</span></p></body></html>"))
        self.auto_tests_log_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">Text Log:</span></p></body></html>"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ALL"))
        self.comboBox.setItemText(1, _translate("MainWindow", "INFO"))
        self.comboBox.setItemText(2, _translate("MainWindow", "ERROR"))
        self.comboBox.setItemText(3, _translate("MainWindow", "CRITICAL"))
        self.comboBox.setItemText(4, _translate("MainWindow", "WARNING"))
        self.comboBox.setItemText(5, _translate("MainWindow", "DEBUG"))
        self.comboBox.setItemText(6, _translate("MainWindow", "NOTICE"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Auto_Tests), _translate("MainWindow", "Auto Tests"))
        self.softphone_text_log_label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Text Log:</span></p></body></html>"))
        self.softphone_softphone_uri_header_label_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Softphone uri:</span></p></body></html>"))
        self.softphone_status_label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">status:</span></p></body></html>"))
        self.softphone_current_status_label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">unregistered</span></p></body></html>"))
        self.softphone_register_label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the softphone\'s ID and PBX\'s IP </span></p><p><span style=\" font-size:10pt;\">to register the softphone:</span></p></body></html>"))
        self.softphone_call_label_1.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the softphone uri you want to dial to:</span></p></body></html>"))
        self.softphone_answer_button_1.setText(_translate("MainWindow", "Answer"))
        self.softphone_call_button_1.setText(_translate("MainWindow", "Call"))
        self.softphone_register_button_1.setText(_translate("MainWindow", "Register"))
        self.softphone_decline_button_1.setText(_translate("MainWindow", "Decline"))
        self.softphone_uri_label_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">null</span></p></body></html>"))
        self.softphone_id_label_1.setText(_translate("MainWindow", "Softphon\'s ID:"))
        self.softphone_pbx_ip_label_1.setText(_translate("MainWindow", "PBX\'s IP:"))
        self.softphone_hangup_button_1.setText(_translate("MainWindow", "Hangup"))
        self.softphone_unregister_button_1.setText(_translate("MainWindow", "Unregister"))
        self.softphone_text_log_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Text Log:</span></p></body></html>"))
        self.softphone_softphone_uri_header_label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Softphone uri:</span></p></body></html>"))
        self.softphone_status_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">status:</span></p></body></html>"))
        self.softphone_current_status_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">unregistered</span></p></body></html>"))
        self.softphone_register_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the softphone\'s ID and PBX\'s IP </span></p><p><span style=\" font-size:10pt;\">to register the softphone:</span></p></body></html>"))
        self.softphone_call_label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the softphone uri you want to dial to:</span></p></body></html>"))
        self.softphone_answer_button_2.setText(_translate("MainWindow", "Answer"))
        self.softphone_call_button_2.setText(_translate("MainWindow", "Call"))
        self.softphone_register_button_2.setText(_translate("MainWindow", "Register"))
        self.softphone_decline_button_2.setText(_translate("MainWindow", "Decline"))
        self.softphone_uri_label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">null</span></p></body></html>"))
        self.softphone_id_label_2.setText(_translate("MainWindow", "Softphon\'s ID:"))
        self.softphone_pbx_ip_label_2.setText(_translate("MainWindow", "PBX\'s IP:"))
        self.softphone_hangup_button_2.setText(_translate("MainWindow", "Hangup"))
        self.softphone_unregister_button_2.setText(_translate("MainWindow", "Unregister"))
        self.softphone_text_log_label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Text Log:</span></p></body></html>"))
        self.softphone_softphone_uri_header_label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Softphone uri:</span></p></body></html>"))
        self.softphone_status_label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">status:</span></p></body></html>"))
        self.softphone_current_status_label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">unregistered</span></p></body></html>"))
        self.softphone_register_label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the softphone\'s ID and PBX\'s IP </span></p><p><span style=\" font-size:10pt;\">to register the softphone:</span></p></body></html>"))
        self.softphone_call_label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt;\">Enter the softphone uri you want to dial to:</span></p></body></html>"))
        self.softphone_answer_button_3.setText(_translate("MainWindow", "Answer"))
        self.softphone_call_button_3.setText(_translate("MainWindow", "Call"))
        self.softphone_register_button_3.setText(_translate("MainWindow", "Register"))
        self.softphone_decline_button_3.setText(_translate("MainWindow", "Decline"))
        self.softphone_uri_label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">null</span></p></body></html>"))
        self.softphone_id_label_3.setText(_translate("MainWindow", "Softphon\'s ID:"))
        self.softphone_pbx_ip_label_3.setText(_translate("MainWindow", "PBX\'s IP:"))
        self.softphone_hangup_button_3.setText(_translate("MainWindow", "Hangup"))
        self.softphone_unregister_button_3.setText(_translate("MainWindow", "Unregister"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Manual_Tests), _translate("MainWindow", "Manual Tests"))
        self.Log_History_Label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Log History:</span></p></body></html>"))
        self.Log_History_Refresh_button.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.History), _translate("MainWindow", "History"))
        self.About_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Creator: Amit Lieba</span></p><p><span style=\" font-size:16pt;\">Company: Unit 108 of the Israeli Air Force</span></p><p><span style=\" font-size:16pt;\">Version: 1.0</span></p><p><span style=\" font-size:16pt;\">The controller is designed to control the VoIP Tester system,</span></p><p><span style=\" font-size:16pt;\">with the help of a user-friendly graphical interface.</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.About), _translate("MainWindow", "About"))
        self.VoIP_Tester_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt;\">VoIP</span></p><p align=\"center\"><span style=\" font-size:24pt;\">Tester</span></p><p align=\"center\"><span style=\" font-size:24pt;\">Controller</span></p></body></html>"))
        self.connect_frame_Connect_button.setText(_translate("MainWindow", "Connect"))
        self.connect_frame_text_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">Please enter the IP and</span></p><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">the Port of the VoIP-Tester</span></p><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">server in order to use </span></p><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">the controller</span></p></body></html>"))
        self.connect_frame_ip_label.setText(_translate("MainWindow", "IP:"))
        self.connect_frame_disconnect_button.setText(_translate("MainWindow", "Disconnect"))
        self.connect_frame_port_label.setText(_translate("MainWindow", "Port:"))

    def autoTestClicked(self):
        self.auto_test_signal.emit(self.auto_tests_pbx_ip_edit_text.toPlainText(), self.auto_tests_amout_edit_text.toPlainText())
    
    def manualTestRegisterClicked(self):
        sender = self.sender()
        if sender == self.softphone_register_button_1:
            self.manual_test_register_signal.emit(0, self.softphone_id_edit_text_1.toPlainText(),
                                                  self.softphone_pbx_ip_edit_text_1.toPlainText())
        elif sender == self.softphone_register_button_2:
            self.manual_test_register_signal.emit(1, self.softphone_id_edit_text_2.toPlainText(),
                                                  self.softphone_pbx_ip_edit_text_2.toPlainText())
        elif sender == self.softphone_register_button_3:
            self.manual_test_register_signal.emit(2, self.softphone_id_edit_text_3.toPlainText(),
                                                  self.softphone_pbx_ip_edit_text_3.toPlainText())
            
    def manualTestUnregisterClicked(self):
        sender = self.sender()
        if sender == self.softphone_unregister_button_1:
            self.manual_test_unregister_signal.emit(0)
        elif sender == self.softphone_unregister_button_2:
            self.manual_test_unregister_signal.emit(1)
        elif sender == self.softphone_unregister_button_3:
            self.manual_test_unregister_signal.emit(2)

    def manualTestCallClicked(self):
        sender = self.sender()
        if sender == self.softphone_call_button_1:
            self.manual_test_call_signal.emit(0, self.softphone_dest_edit_text_1.toPlainText())
        elif sender == self.softphone_call_button_2:
            self.manual_test_call_signal.emit(1, self.softphone_dest_edit_text_2.toPlainText())
        elif sender == self.softphone_call_button_3:
            self.manual_test_call_signal.emit(2, self.softphone_dest_edit_text_3.toPlainText())

    def manualTestHangupClicked(self):
        sender = self.sender()
        if sender == self.softphone_hangup_button_1:
            self.manual_test_hangup_signal.emit(0)
        elif sender == self.softphone_hangup_button_2:
            self.manual_test_hangup_signal.emit(1)
        elif sender == self.softphone_hangup_button_3:
            self.manual_test_hangup_signal.emit(2)

    def manualTestAnswerClicked(self):
        sender = self.sender()
        if sender == self.softphone_answer_button_1:
            self.manual_test_answer_signal.emit(0)
        elif sender == self.softphone_answer_button_2:
            self.manual_test_answer_signal.emit(1)
        elif sender == self.softphone_answer_button_3:
            self.manual_test_answer_signal.emit(2)
    
    def manualTestDeclineClicked(self):
        sender = self.sender()
        if sender == self.softphone_decline_button_1:
            self.manual_test_decline_signal.emit(0)
        elif sender == self.softphone_decline_button_2:
            self.manual_test_decline_signal.emit(1)
        elif sender == self.softphone_decline_button_3:
            self.manual_test_decline_signal.emit(2)

    
    
    def connectClicked(self):
        self.connect_signal.emit(self.connect_frame_ip_edit_text.toPlainText(),
                                 self.connect_frame_port_edit_text.toPlainText())
    
    def disconnectClicked(self):
        self.disconnect_signal.emit()

    def printLog(self, text_browser : QtWidgets.QTextBrowser, value : str):
        text_browser.setText(value)

    def itemClicked(self, item):
        self.item_clicked_signal.emit(item.text())
    
    def openPopupWindow(self, data):
        popup_window = LogPopupWindow(data)
        popup_window.exec_()

    def refreshHeaders(self):
        self.refreshHeaders_signal.emit()

