from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_MainWindow(QtWidgets.QMainWindow):

    auto_test_signal = QtCore.pyqtSignal(str)
    manual_test_signal = QtCore.pyqtSignal(str)
    connect_signal = QtCore.pyqtSignal(str, str)
    disconnect_signal = QtCore.pyqtSignal()

    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setObjectName("MainWindow")
        self.resize(1079, 752)
        self.setAutoFillBackground(False)
        self.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(220, 0, 861, 761))
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setObjectName("tabWidget")
        self.Auto_Tests = QtWidgets.QWidget()
        self.Auto_Tests.setObjectName("Auto_Tests")
        self.auto_tests_main_label = QtWidgets.QLabel(self.Auto_Tests)
        self.auto_tests_main_label.setGeometry(QtCore.QRect(10, 30, 481, 71))
        self.auto_tests_main_label.setObjectName("auto_tests_main_label")
        self.auto_tests_amout_edit_text = QtWidgets.QTextEdit(self.Auto_Tests)
        self.auto_tests_amout_edit_text.setGeometry(QtCore.QRect(300, 220, 261, 31))
        self.auto_tests_amout_edit_text.setObjectName("auto_tests_amout_edit_text")
        self.auto_tests_button = QtWidgets.QPushButton(self.Auto_Tests)
        self.auto_tests_button.setGeometry(QtCore.QRect(630, 190, 75, 23))
        self.auto_tests_button.setObjectName("auto_tests_button")
        self.auto_tests_pbx_ip_edit_text = QtWidgets.QTextEdit(self.Auto_Tests)
        self.auto_tests_pbx_ip_edit_text.setGeometry(QtCore.QRect(300, 150, 261, 31))
        self.auto_tests_pbx_ip_edit_text.setObjectName("auto_tests_pbx_ip_edit_text")
        self.auto_tests_pbx_ip_label = QtWidgets.QLabel(self.Auto_Tests)
        self.auto_tests_pbx_ip_label.setGeometry(QtCore.QRect(140, 150, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.auto_tests_pbx_ip_label.setFont(font)
        self.auto_tests_pbx_ip_label.setObjectName("auto_tests_pbx_ip_label")
        self.auto_tests_amout_label = QtWidgets.QLabel(self.Auto_Tests)
        self.auto_tests_amout_label.setGeometry(QtCore.QRect(140, 220, 112, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.auto_tests_amout_label.setFont(font)
        self.auto_tests_amout_label.setObjectName("auto_tests_amout_label")
        self.auto_tests_text_log_text_browser = QtWidgets.QTextBrowser(self.Auto_Tests)
        self.auto_tests_text_log_text_browser.setGeometry(QtCore.QRect(-5, 291, 861, 441))
        self.auto_tests_text_log_text_browser.setObjectName("auto_tests_text_log_text_browser")
        self.tabWidget.addTab(self.Auto_Tests, "")
        self.Manual_Tests = QtWidgets.QWidget()
        self.Manual_Tests.setObjectName("Manual_Tests")
        self.manual_tests_label = QtWidgets.QLabel(self.Manual_Tests)
        self.manual_tests_label.setGeometry(QtCore.QRect(70, 40, 701, 81))
        self.manual_tests_label.setObjectName("manual_tests_label")
        self.manual_tests_edit_text = QtWidgets.QTextEdit(self.Manual_Tests)
        self.manual_tests_edit_text.setGeometry(QtCore.QRect(290, 130, 271, 31))
        self.manual_tests_edit_text.setObjectName("manual_tests_edit_text")
        self.manual_tests_button = QtWidgets.QPushButton(self.Manual_Tests)
        self.manual_tests_button.setGeometry(QtCore.QRect(380, 170, 75, 23))
        self.manual_tests_button.setObjectName("manual_tests_button")
        self.tabWidget.addTab(self.Manual_Tests, "")
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.tabWidget.addTab(self.Settings, "")
        self.About = QtWidgets.QWidget()
        self.About.setObjectName("About")
        self.tabWidget.addTab(self.About, "")
        self.VoIP_Tester_Label = QtWidgets.QLabel(self.centralwidget)
        self.VoIP_Tester_Label.setGeometry(QtCore.QRect(0, 0, 211, 131))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.VoIP_Tester_Label.setFont(font)
        self.VoIP_Tester_Label.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.VoIP_Tester_Label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.VoIP_Tester_Label.setAutoFillBackground(True)
        self.VoIP_Tester_Label.setScaledContents(True)
        self.VoIP_Tester_Label.setObjectName("VoIP_Tester_Label")
        self.connect_frame = QtWidgets.QFrame(self.centralwidget)
        self.connect_frame.setGeometry(QtCore.QRect(0, 140, 221, 611))
        self.connect_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.connect_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.connect_frame.setObjectName("connect_frame")
        self.connect_frame_Connect_button = QtWidgets.QPushButton(self.connect_frame)
        self.connect_frame_Connect_button.setGeometry(QtCore.QRect(70, 360, 75, 23))
        self.connect_frame_Connect_button.setObjectName("connect_frame_Connect_button")
        self.connect_frame_ip_edit_text = QtWidgets.QTextEdit(self.connect_frame)
        self.connect_frame_ip_edit_text.setGeometry(QtCore.QRect(10, 240, 181, 31))
        self.connect_frame_ip_edit_text.setObjectName("connect_frame_ip_edit_text")
        self.connect_frame_text_label = QtWidgets.QLabel(self.connect_frame)
        self.connect_frame_text_label.setGeometry(QtCore.QRect(10, 90, 211, 101))
        self.connect_frame_text_label.setObjectName("connect_frame_text_label")
        self.connect_frame_ip_label = QtWidgets.QLabel(self.connect_frame)
        self.connect_frame_ip_label.setGeometry(QtCore.QRect(10, 220, 47, 13))
        self.connect_frame_ip_label.setObjectName("connect_frame_ip_label")
        self.connect_frame_port_label = QtWidgets.QLabel(self.connect_frame)
        self.connect_frame_port_label.setGeometry(QtCore.QRect(10, 290, 47, 13))
        self.connect_frame_port_label.setObjectName("connect_frame_port_label")
        self.connect_frame_port_edit_text = QtWidgets.QTextEdit(self.connect_frame)
        self.connect_frame_port_edit_text.setGeometry(QtCore.QRect(10, 310, 181, 31))
        self.connect_frame_port_edit_text.setObjectName("connect_frame_port_edit_text")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(self)

        self.auto_tests_button.clicked.connect(self.autoTestClicked)
        self.manual_tests_button.clicked.connect(self.manualTestClicked)
        self.connect_frame_Connect_button.clicked.connect(self.connectClicked)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.auto_tests_main_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Please Enter the required details below:</span></p></body></html>"))
        self.auto_tests_amout_edit_text.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8.25pt;\"><br /></p></body></html>"))
        self.auto_tests_button.setText(_translate("MainWindow", "Send"))
        self.auto_tests_pbx_ip_label.setText(_translate("MainWindow", "PBX IP:"))
        self.auto_tests_amout_label.setText(_translate("MainWindow", "Amout of calls:"))
        self.auto_tests_text_log_text_browser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Text log:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Auto_Tests), _translate("MainWindow", "Auto Tests"))
        self.manual_tests_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">Please enter the number of softphones you want to create </span></p><p align=\"center\"><span style=\" font-size:16pt;\">(Max. 5)</span></p></body></html>"))
        self.manual_tests_button.setText(_translate("MainWindow", "Send"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Manual_Tests), _translate("MainWindow", "Manual Tests"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("MainWindow", "Settings"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.About), _translate("MainWindow", "About"))
        self.VoIP_Tester_Label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">VoIP</span></p><p align=\"center\"><span style=\" font-size:28pt;\">Tester</span></p></body></html>"))
        self.connect_frame_Connect_button.setText(_translate("MainWindow", "Connect"))
        self.connect_frame_text_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">Please enter IP and</span></p><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">the port of the server</span></p><p align=\"justify\"><span style=\" font-size:10pt; font-weight:600;\">inorder to use the tester</span></p></body></html>"))
        self.connect_frame_ip_label.setText(_translate("MainWindow", "IP:"))
        self.connect_frame_port_label.setText(_translate("MainWindow", "Port:"))

    def autoTestClicked(self):
        self.auto_test_signal.emit(self.auto_tests_pbx_ip_edit_text.toPlainText() + "," + self.auto_tests_amout_edit_text.toPlainText())
    
    def manualTestClicked(self):
        self.manual_test_signal.emit(self.manual_tests_edit_text.toPlainText())
    
    def connectClicked(self):
        self.connect_signal.emit(self.connect_frame_ip_edit_text.toPlainText(), self.connect_frame_port_edit_text.toPlainText())
    
    def disconnectClicked(self):
        self.disconnect_signal.emit()