from enum import Enum

class VTCPOpcode(Enum):
    VTCP_CONNECT_REQ = 1
    VTCP_CONNECT_RES = 2

    VTCP_DISCONNECT_REQ = 3
    VTCP_DISCONNECT_RES = 4

    VTCP_AUTO_TEST_REQ = 5
    VTCP_AUTO_TEST_RES = 6

    VTCP_MANUAL_TEST_REQ = 7
    VTCP_MANUAL_TEST_RES = 8